version: 2

models:
  - name: dim_products_scd2
    description: "Product dimension table with SCD Type 2 for tracking historical changes"
    columns:
      - name: surrogate_key
        description: "Surrogate key combining product_id and timestamp"
        tests:
          - unique
          - not_null

      - name: product_id
        description: "Natural business key for the product"
        tests:
          - not_null

      - name: title
        description: "Product title/name"
        tests:
          - not_null

      - name: price
        description: "Product price"
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: 0
              inclusive: false

      - name: valid_from
        description: "Start date when this version became active"
        tests:
          - not_null

      - name: is_current
        description: "Flag indicating if this is the current active record"
        tests:
          - not_null
          - accepted_values:
              values: [true, false]

      - name: category
        description: "Product category"
        tests:
          - not_null

      - name: currency
        description: "Price currency code"
        tests:
          - accepted_values:
              values: ["USD", "EUR", "GBP", "CAD"]
